#pragma once

#include <cstddef>

struct EmbeddedFilePayload {
    const wchar_t* relativePath;
    const unsigned char* bytes;
    std::size_t size;
};

// Auto-generated by installer/Generate-InstallerPayload.ps1
// This placeholder keeps source builds clean before release packaging.
inline constexpr unsigned char kPlaceholderPayloadBytes[] = {0x00};
inline constexpr EmbeddedFilePayload kEmbeddedFiles[] = {
    { L"", kPlaceholderPayloadBytes, 0 }
};
inline constexpr std::size_t kEmbeddedFileCount = 0;
