param(
    [string]$BuildOutputDir = "$PSScriptRoot\..\build-msvc",
    [string]$OutputHeader = "$PSScriptRoot\..\src\generated_payload.h"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$buildRoot = (Resolve-Path $BuildOutputDir).Path

$mustHave = @(
    "WallpaperXEditor.exe",
    "WallpaperXStartup.exe"
)

foreach ($name in $mustHave) {
    $full = Join-Path $buildRoot $name
    if (-not (Test-Path -LiteralPath $full)) {
        throw "Missing required payload file: $full"
    }
}

function Escape-CppWideString {
    param([string]$Value)
    return ($Value -replace "\\", "\\\\") -replace '"', '\"'
}

function Convert-ToCppByteArray {
    param(
        [byte[]]$Bytes,
        [string]$SymbolName
    )

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("inline constexpr unsigned char $SymbolName[] = {")
    for ($i = 0; $i -lt $Bytes.Length; $i++) {
        if (($i % 12) -eq 0) {
            [void]$sb.Append("    ")
        }
        [void]$sb.AppendFormat("0x{0:X2}", $Bytes[$i])
        if ($i -lt ($Bytes.Length - 1)) {
            [void]$sb.Append(", ")
        }
        if ((($i + 1) % 12) -eq 0) {
            [void]$sb.AppendLine()
        }
    }
    if (($Bytes.Length % 12) -ne 0) {
        [void]$sb.AppendLine()
    }
    [void]$sb.AppendLine("};")
    return $sb.ToString()
}

# Runtime payload selection for release installer.
$runtimeExtensions = @(".exe", ".dll", ".json", ".dat", ".pak", ".bin", ".cfg", ".ini")
$runtimeFiles = New-Object System.Collections.Generic.List[System.IO.FileInfo]

Get-ChildItem -Path $buildRoot -File | ForEach-Object {
    $ext = $_.Extension.ToLowerInvariant()
    if ($ext -eq ".exe") {
        if ($mustHave -contains $_.Name) {
            [void]$runtimeFiles.Add($_)
        }
        return
    }
    if ($runtimeExtensions -contains $ext) {
        [void]$runtimeFiles.Add($_)
    }
}

# Optional runtime directories commonly used for shipped assets/dependencies.
$optionalDirs = @("libvlc", "plugins", "assets", "resources")
foreach ($dir in $optionalDirs) {
    $fullDir = Join-Path $buildRoot $dir
    if (Test-Path -LiteralPath $fullDir) {
        Get-ChildItem -Path $fullDir -Recurse -File | ForEach-Object {
            [void]$runtimeFiles.Add($_)
        }
    }
}

if ($runtimeFiles.Count -eq 0) {
    throw "No runtime payload files found in $buildRoot"
}

$headerParts = New-Object System.Collections.Generic.List[string]
[void]$headerParts.Add("#pragma once")
[void]$headerParts.Add("")
[void]$headerParts.Add("#include <cstddef>")
[void]$headerParts.Add("")
[void]$headerParts.Add("struct EmbeddedFilePayload {")
[void]$headerParts.Add("    const wchar_t* relativePath;")
[void]$headerParts.Add("    const unsigned char* bytes;")
[void]$headerParts.Add("    std::size_t size;")
[void]$headerParts.Add("};")
[void]$headerParts.Add("")
[void]$headerParts.Add("// Auto-generated by installer/Generate-InstallerPayload.ps1")
[void]$headerParts.Add("")

$manifestEntries = New-Object System.Collections.Generic.List[string]
$index = 0
$totalBytes = 0

$distinctFiles = $runtimeFiles | Sort-Object FullName -Unique
foreach ($file in $distinctFiles) {
    $relative = $file.FullName.Substring($buildRoot.Length).TrimStart('\','/')
    $relative = $relative -replace "/", "\"
    $symbol = "kPayloadData$index"
    $bytes = [System.IO.File]::ReadAllBytes($file.FullName)
    $totalBytes += $bytes.Length

    [void]$headerParts.Add((Convert-ToCppByteArray -Bytes $bytes -SymbolName $symbol))

    $escapedPath = Escape-CppWideString $relative
    [void]$manifestEntries.Add("    { L`"$escapedPath`", $symbol, sizeof($symbol) }")
    $index++
}

[void]$headerParts.Add("inline constexpr EmbeddedFilePayload kEmbeddedFiles[] = {")
[void]$headerParts.Add(($manifestEntries -join ",`r`n"))
[void]$headerParts.Add("};")
[void]$headerParts.Add("inline constexpr std::size_t kEmbeddedFileCount = sizeof(kEmbeddedFiles) / sizeof(kEmbeddedFiles[0]);")
[void]$headerParts.Add("")

Set-Content -Path $OutputHeader -Value ($headerParts -join "`r`n") -Encoding Ascii

Write-Host "Generated payload header: $OutputHeader"
Write-Host "Embedded files: $($distinctFiles.Count)"
Write-Host "Total payload bytes: $totalBytes"
